practice/config/routes.rb
Rails.application.routes.draw do
  get 'comments/index'

  get 'comments/show'

  get 'comments/create'

  get 'comments/new'

  get 'comments/edit'

  get 'comments/update'

  get 'comments/destroy'

  # get 'posts/index'
  #
  # get 'posts/show'
  #
  # get 'posts/new'
  #
  # get 'posts/create'
  #
  # get 'posts/destroy'

  devise_for :users
  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'

  resources :posts do
    resources :comments
  end

end

practice/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

practice/app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

practice/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

practice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

practice/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post
    @comment.user = current_user

    if comment.save
      flash[:notice]="Comment has been saved."
      redirect_to @comment
    else
      flash[:error]="Comment could not be saved."
      render :new
    end
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.save
      flash[:notice]="Comment was saved successfully."
      redirect_to @comment
    else
      flash[:error]="Comment could not be saved."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comment.find(params[:id])
    if @comment.destroy
      flash[:notice] = "Comment was deleted successfully."
      redirect_to @post
    else
      flash[:error] = "Comment failed to delete."
      render :show
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

practice/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      flash[:notice] = "Post had been saved."
      redirect_to @post
    else
      flash[:error] = "Post could not be saved."
      render :new
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.assign_attributes(post_params)
    if @post.save
      flash[:notice]="Post has been updated."
      redirect_to @post
    else
      flash[:error]="Post could not be updated."
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice]="Post has been deleted."
      render :index
    else
      flash[:error]="Post could not be deleted."
      redirect_to @post
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end

end

practice/app/controllers/users_controller.rb
class UsersController < ApplicationController
end

practice/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

practice/app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end
end

practice/app/helpers/comments_helper.rb
module CommentsHelper
end

practice/app/helpers/posts_helper.rb
module PostsHelper
end

practice/app/helpers/users_helper.rb
module UsersHelper
end

practice/app/helpers/welcome_helper.rb
module WelcomeHelper
end

practice/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

practice/app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

practice/app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

practice/app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

practice/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

practice/app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

practice/app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

practice/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%=link_to "Home", welcome_index_path%></li>
      <li><%=link_to "About", welcome_about_path%></li>
      <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'%></li>
      <li><%= link_to "Post", posts_path%></li>
    </ul>

  </div>

<%= yield %>

</body>
</html>

practice/app/views/posts/_form.html.erb
<%= form_for [post] do |f| %>
  <% if post.errors.any? %>

    <div class="alert alert-danger">

      <h4><%= pluralize(post.errors.count, "error") %>.</h4>
      <ul>
        <% post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_group_tag(post.errors[:title]) do %>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  <% end %>

  <%= form_group_tag(post.errors[:body]) do %>
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
  <% end %>


  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

practice/app/views/posts/_post.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, post_path(post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.email %> <br>
    </small>
  </div>
</div>

practice/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

practice/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

practice/app/views/posts/index.html.erb
<div class="container">
  <h1>Posts</h1>
  <div class="row">
    <div class="col-md-8">
      <%=link_to "Add a New Post", new_post_path, class: 'btn btn-success'%>
      <%=render @posts%>
    </div>
  </div>
</div>

practice/app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>
  <div class="row">
    <div class="col-md-4">
      <p>Guidelines for posts</p>
      <ul>
        <li>Make it interesting.</li>
      </ul>
    </div>

    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
  </div>
</div>

practice/app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h3>Post by <%=@post.user.email%></h3>
      <p><%= @post.body %></p>
      <div class="row">
        <div class="col-md-8">
        <h4>Comments</h4>
        </div>
      </div>
    </div>
  </div>
</div>

practice/app/views/welcome/about.html.erb
<div class="container">
  <h1>Welcome#about</h1>
  <p>Here's the about page. Fascinating.</p>
</div>

practice/app/views/welcome/index.html.erb
<div class="container">
  <h1>Welcome#index</h1>
  <p id="index-title">Welcome to a practice app <%=current_user.email%></p>
  <div class="posts">Post UNO</div>
  <div class="posts">Post DOS</div>
  <section>Content in section</section>
</div>